=== YaroslavGooD/xml/movie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.dubenko.dev/catalog" 
xmlns:catalog="http://www.dubenko.dev/catalog" 
xmlns:autorzy="http://www.dubenko.dev/catalog" 
xmlns:mov="http://www.dubenko.dev/catalog" 
xmlns:com="http://www.dubenko.dev/catalog" 
elementFormDefault="qualified">

  <!-- SimpleType -->
  <xs:simpleType name="ShortString">
    <xs:restriction base="xs:string">
      <xs:minLength value="2" />
      <xs:maxLength value="50" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="language">
    <xs:restriction base="xs:string">
      <xs:enumeration value="pl" />
      <xs:enumeration value="en" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="curr">
    <xs:restriction base="xs:string">
      <xs:enumeration value="usd" />
      <xs:enumeration value="pln" />
      <xs:enumeration value="eur" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="timeF">
    <xs:restriction base="xs:string">
      <xs:enumeration value="min" />
      <xs:enumeration value="hour" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typ_date">
    <xs:restriction base="xs:date">
      <xs:minInclusive value="1200-01-01" />
      <xs:maxInclusive value="2025-12-31" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Group -->
  <xs:group name="Persone">
    <xs:sequence>
      <xs:element name="name" type="autorzy:ShortString" />
      <xs:element name="surname" type="autorzy:ShortString" />
    </xs:sequence>
  </xs:group>

  <xs:attributeGroup name="movieAttr">
    <xs:attribute name="IdMovie" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:ID">
          <xs:pattern value="[m]([0-9])*" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IdCompany" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:IDREF">
          <xs:pattern value="[c]([0-9])*" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>

  <!-- ComplexType -->
  <xs:complexType name="author">
    <xs:sequence>
      <xs:group ref="autorzy:Persone" />
      <xs:element ref="autorzy:index_id" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="money">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="currency" type="mov:curr" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Meta data -->
  <xs:element name="author1" type="autorzy:author" />

  <xs:element name="author2" type="autorzy:author" />

  <xs:element name="index_id">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:pattern value="[0-9]{6}" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="entire" type="autorzy:ShortString" />

  <xs:element name="proj_authors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="autorzy:author1" />
        <xs:element ref="autorzy:author2" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="lab_title" type="autorzy:ShortString" />

  <xs:element name="document_information">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="autorzy:lab_title" />
        <xs:element ref="autorzy:proj_authors" />
        <xs:element ref="autorzy:entire" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Movies -->
  <xs:element name="title">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="mov:ShortString">
          <xs:attribute name="lang" type="mov:language" use="optional" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="country" type="mov:ShortString" />

  <xs:element name="countries">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mov:country" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="date" type="mov:typ_date" />

  <xs:element name="budget" type="mov:money" />

  <xs:element name="worldwide_gross" type="mov:money" />

  <xs:element name="runtime">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="timeFormat" type="mov:timeF" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rate" type="xs:float" />

  <xs:element name="category" type="xs:string" />
  
  <xs:element name="movie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mov:title" />
        <xs:choice>
          <xs:element ref="mov:countries" />
          <xs:element ref="mov:country" />
        </xs:choice>
        <xs:element ref="mov:date" />
        <xs:element ref="mov:budget" />
        <xs:element ref="mov:worldwide_gross" />
        <xs:element ref="mov:runtime" />
        <xs:element ref="mov:rate" />
        <xs:element ref="mov:category" />
      </xs:sequence>
      <xs:attributeGroup ref="mov:movieAttr" />
    </xs:complexType>
  </xs:element>

  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mov:movie" maxOccurs="unbounded" minOccurs="1" />
      </xs:sequence>
    </xs:complexType>
    <xs:key name="movieID">
      <xs:selector xpath="mov:movie" />
      <xs:field xpath="@IdMovie" />
    </xs:key>
  </xs:element>

  <!-- Companies -->
  <xs:element name="companyTitle" type="com:ShortString" />
  <xs:element name="founded">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="com:typ_date">
          <xs:attribute name="isExactDate" type="xs:boolean" use="optional"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="chairman" type="com:ShortString" />

  <xs:element name="president" type="com:ShortString" />
  
  <xs:element name="founder" type="com:ShortString" />

  <xs:element name="founders">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:founder" maxOccurs="unbounded" minOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="headquarter" type="com:ShortString" />

  <xs:element name="company">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:companyTitle" />
        <xs:element ref="com:founded" />
        <xs:choice>
          <xs:element ref="com:chairman" />
          <xs:element ref="com:president" />
        </xs:choice>
        <xs:element ref="com:founders" />
        <xs:element ref="com:headquarter" />
      </xs:sequence>
      <xs:attribute name="IdCompany" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:ID">
            <xs:pattern value="[c]([0-9])+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="companies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="com:company" maxOccurs="unbounded" minOccurs="1" />
      </xs:sequence>
    </xs:complexType>

    <xs:key name="companyID">
      <xs:selector xpath="com:company" />
      <xs:field xpath="@IdCompany" />
    </xs:key>
  </xs:element>

<!-- Root elements -->
  <xs:element name="movie_catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="autorzy:document_information" />
        <xs:element ref="mov:movies" />
        <xs:element ref="com:companies" />
      </xs:sequence>
    </xs:complexType>

<!-- Key ref -->
    <xs:keyref name="refCompany" refer="com:companyID">
      <xs:selector xpath="catalog:movies/movie" />
      <xs:field xpath="@IdCompany" />
    </xs:keyref>
  </xs:element>

</xs:schema>

=== YaroslavGooD/xml/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE catalog:movie_catalog SYSTEM "movie.dtd"> -->
<?xml-stylesheet?>
<catalog:movie_catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:catalog="http://www.dubenko.dev/catalog" 
xsi:schemaLocation="http://www.dubenko.dev/catalog movie.xsd">
  
  <!-- Metadata -->
  <autorzy:document_information xmlns:autorzy="http://www.dubenko.dev/catalog">
    <autorzy:lab_title>Movie viewer</autorzy:lab_title>
    <autorzy:proj_authors>
      <autorzy:author1>
        <autorzy:name>Yaroslav</autorzy:name>
        <autorzy:surname>Horetskyi</autorzy:surname>
        <autorzy:index_id>211714</autorzy:index_id>
      </autorzy:author1>
      <autorzy:author2>
        <autorzy:name>Oleksandr</autorzy:name>
        <autorzy:surname>Dubenko</autorzy:surname>
        <autorzy:index_id>211651</autorzy:index_id>
      </autorzy:author2>
    </autorzy:proj_authors>
    <autorzy:entire>Movie catalog</autorzy:entire>
  </autorzy:document_information>

  <!-- Movies -->
  <mov:movies xmlns:mov="http://www.dubenko.dev/catalog">
    <mov:movie IdMovie="m1" IdCompany="c1">
      <mov:title lang="pl">Skazani na Shawshank</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>1994-09-10</mov:date>
      <mov:budget currency="usd">25000000</mov:budget>
      <mov:worldwide_gross currency="usd">58500000</mov:worldwide_gross>
      <mov:runtime timeFormat="min">142</mov:runtime>
      <mov:rate>9.3</mov:rate>
      <mov:category>Drama</mov:category>
    </mov:movie>
    <!-- ^Castle^ -->

    <mov:movie IdMovie="m2" IdCompany="c2">
      <mov:title lang="pl">Rodzina od zaraz</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-11-16</mov:date>
      <mov:budget currency="usd">48000000</mov:budget>
      <mov:worldwide_gross currency="usd">81025217</mov:worldwide_gross>
      <mov:runtime timeFormat="min">118</mov:runtime>
      <mov:rate>7.4</mov:rate>
      <mov:category>Comedy, Drama</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m3" IdCompany="c2">
      <mov:title lang="pl">Operacja Overlord</mov:title>
      <mov:countries>
        <mov:country>USA</mov:country>
        <mov:country>Canada</mov:country>
      </mov:countries>
      <mov:date>2018-09-22</mov:date>
      <mov:budget currency="usd">38000000</mov:budget>
      <mov:worldwide_gross currency="usd">21704844</mov:worldwide_gross>
      <mov:runtime timeFormat="min">110</mov:runtime>
      <mov:rate>6.8</mov:rate>
      <mov:category>Action, Adventure, Horror</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m4" IdCompany="c2">
      <mov:title lang="pl">Ojciec chrzestny</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>1972-03-14</mov:date>
      <mov:budget currency="usd">6000000</mov:budget>
      <mov:worldwide_gross currency="usd">245066411</mov:worldwide_gross>
      <mov:runtime timeFormat="min">175</mov:runtime>
      <mov:rate>9.3</mov:rate>
      <mov:category>Crime, Drama</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m5" IdCompany="c2">
      <mov:title lang="pl">Interstellar</mov:title>
      <mov:countries>
        <mov:country>UK</mov:country>
        <mov:country>USA</mov:country>
      </mov:countries>
      <mov:date>2014-10-26</mov:date>
      <mov:budget currency="usd">165000000</mov:budget>
      <mov:worldwide_gross currency="usd">675020017</mov:worldwide_gross>
      <mov:runtime timeFormat="min">169</mov:runtime>
      <mov:rate>8.6</mov:rate>
      <mov:category>Adventure, Drama, Sci-Fi</mov:category>
    </mov:movie>
    <!-- ^Paramaunt^ -->

    <mov:movie IdMovie="m6" IdCompany="c3">
      <mov:title lang="pl">Narodziny gwiazdy</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-08-31</mov:date>
      <mov:budget currency="usd">36000000</mov:budget>
      <mov:worldwide_gross currency="usd">214601602</mov:worldwide_gross>
      <mov:runtime timeFormat="min">148</mov:runtime>
      <mov:rate>7.8</mov:rate>
      <mov:category>Drama, Music, Romance</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m7" IdCompany="c3">
      <mov:title lang="pl">Aquaman</mov:title>
      <mov:countries>
        <mov:country>Australia</mov:country>
        <mov:country>USA</mov:country>
      </mov:countries>
      <mov:date>1994-09-10</mov:date>
      <mov:budget currency="usd">25000000</mov:budget>
      <mov:worldwide_gross currency="usd">58500000</mov:worldwide_gross>
      <mov:runtime timeFormat="min">142</mov:runtime>
      <mov:rate>7.3</mov:rate>
      <mov:category>Action, Adventure, Fantasy</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m8" IdCompany="c3">
      <mov:title lang="pl">Creed II</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-11-14</mov:date>
      <mov:budget currency="usd">50000000</mov:budget>
      <mov:worldwide_gross currency="usd">175431419</mov:worldwide_gross>
      <mov:runtime timeFormat="min">130</mov:runtime>
      <mov:rate>7.3</mov:rate>
      <mov:category>Drama, Sport</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m9" IdCompany="c3">
      <mov:title lang="pl">Legion samobójców</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2016-08-01</mov:date>
      <mov:budget currency="usd">175000000</mov:budget>
      <mov:worldwide_gross currency="usd">746846894</mov:worldwide_gross>
      <mov:runtime timeFormat="min">134</mov:runtime>
      <mov:rate>6.1</mov:rate>
      <mov:category>Action, Adventure, Fantasy</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m10" IdCompany="c3">
      <mov:title lang="pl">Wonder Woman</mov:title>
      <mov:countries>
        <mov:country>China</mov:country>
        <mov:country>USA</mov:country>
        <mov:country>Hong Kong</mov:country>
      </mov:countries>
      <mov:date>2017-05-15</mov:date>
      <mov:budget currency="usd">149000000</mov:budget>
      <mov:worldwide_gross currency="usd">821763408</mov:worldwide_gross>
      <mov:runtime timeFormat="min">141</mov:runtime>
      <mov:rate>7.5</mov:rate>
      <mov:category>Action, Adventure, Fantasy</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m11" IdCompany="c3">
      <mov:title lang="en">Ocean's 8</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-06-05</mov:date>
      <mov:budget currency="usd">70000000</mov:budget>
      <mov:worldwide_gross currency="usd">283980167</mov:worldwide_gross>
      <mov:runtime timeFormat="min">110</mov:runtime>
      <mov:rate>6.2</mov:rate>
      <mov:category>Action, Comedy, Crime</mov:category>
    </mov:movie>
    <!-- ^Warner Bros^ -->

    <mov:movie IdMovie="m12" IdCompany="c4">
      <mov:title lang="pl">Drapacz chmur</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-07-11</mov:date>
      <mov:budget currency="usd">125000000</mov:budget>
      <mov:worldwide_gross currency="usd">292351275</mov:worldwide_gross>
      <mov:runtime timeFormat="min">102</mov:runtime>
      <mov:rate>5.8</mov:rate>
      <mov:category>Action, Adventure, Thriller</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m13" IdCompany="c4">
      <mov:title lang="pl">Kong: Wyspa Czaszki</mov:title>
      <mov:countries>
        <mov:country>China</mov:country>
        <mov:country>USA</mov:country>
      </mov:countries>
      <mov:date>2017-02-28</mov:date>
      <mov:budget currency="usd">185000000</mov:budget>
      <mov:worldwide_gross currency="usd">566652812</mov:worldwide_gross>
      <mov:runtime timeFormat="min">118</mov:runtime>
      <mov:rate>6.6</mov:rate>
      <mov:category>Action, Adventure, Fantasy</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m14" IdCompany="c4">
      <mov:title lang="pl">Jurassic World: Upadłe królestwo </mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2018-05-21</mov:date>
      <mov:budget currency="usd">170000000</mov:budget>
      <mov:worldwide_gross currency="usd">1309484461</mov:worldwide_gross>
      <mov:runtime timeFormat="min">128</mov:runtime>
      <mov:rate>6.2</mov:rate>
      <mov:category>Action, Adventure, Sci-Fi</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m15" IdCompany="c4">
      <mov:title lang="pl">Incepcja</mov:title>
      <mov:countries>
        <mov:country>UK</mov:country>
        <mov:country>USA</mov:country>
      </mov:countries>
      <mov:date>2010-07-08</mov:date>
      <mov:budget currency="usd">160000000</mov:budget>
      <mov:worldwide_gross currency="usd">825532764</mov:worldwide_gross>
      <mov:runtime timeFormat="min">148</mov:runtime>
      <mov:rate>8.8</mov:rate>
      <mov:category>Action, Adventure, Sci-Fi</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m16" IdCompany="c4">
      <mov:title lang="pl">Watchmen- Strażnicy</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>1994-09-10</mov:date>
      <mov:budget currency="usd">25000000</mov:budget>
      <mov:worldwide_gross currency="usd">58500000</mov:worldwide_gross>
      <mov:runtime timeFormat="min">142</mov:runtime>
      <mov:rate>9.3</mov:rate>
      <mov:category>Drama</mov:category>
    </mov:movie>
    <mov:movie IdMovie="m17" IdCompany="c4">
      <mov:title lang="pl">Skazani na Shawshank</mov:title>
      <mov:country>USA</mov:country>
      <mov:date>2009-02-23</mov:date>
      <mov:budget currency="usd">130000000</mov:budget>
      <mov:worldwide_gross currency="usd">185258983</mov:worldwide_gross>
      <mov:runtime timeFormat="min">215</mov:runtime>
      <mov:rate>7.6</mov:rate>
      <mov:category>Action, Drama, Mystery</mov:category>
    </mov:movie>
    <!-- ^Legendary^ -->

    <mov:movie IdMovie="m18" IdCompany="c5">
      <mov:title lang="pl">Bohemian Rhapsody</mov:title>
      <mov:countries>
